export enum LegislationTag {
  ALKOHOL = "alkohol",
  APTEKI = "apteki",
  BUDOWNICTWO = "budownictwo",
  COMPLIANCE = "compliance",
  COVID_19 = "COVID-19",
  DANE_OSOBOWE = "dane osobowe",
  ENERGETYKA = "energetyka",
  INSTRUMENTY_FINANSOWE = "instrumenty finansowe",
  OCHRONA_SRODOWISKA = "ochrona środowiska",
  ODPADY = "odpady",
  OSWIATA = "oświata",
  PODATKI = "podatki",
  PODMIOTY_LECZNICZE = "podmioty lecznicze",
  POSTEPOWANIA_ADMINISTRACYJNE = "postępowania administracyjne",
  PRACOWNICY = "pracownicy",
  PRAWO_KONKURENCJI = "prawo konkurencji",
  PROCES_CYWILNY = "proces cywilny",
  PROCES_KARNY = "proces karny",
  PRODUKTY_LECZNICZNE = "produkty leczniczne",
  PRZEDSIEBIORCY = "przedsiębiorcy",
  REKLAMA = "reklama",
  SZKOLNICTWO_WYZSZE = "szkolnictwo wyższe",
  WYROBY_MEDYCZNE = "wyroby medyczne",
  WYROBY_TYTONIOWE = "wyroby tytoniowe",
  ZAMOWIENIA_PUBLICZNE = "zamówienia publiczne"
}
